"""Flatten occam's MIT solver into a single self-contained module: agent/occam_bundle.py.

occam (github.com/TheRealSeanDonahoe/occam, MIT) is a $0, no-LLM, reset-replay ARC-AGI-3
solver. Its solver/ package spans several modules that import each other via `from solver.X`.
For the Kaggle splice (which ships only files we write), we concatenate those modules in
dependency order into ONE importable module, stripping the internal `from solver.*` imports.

Run:  python scripts/bundle_occam.py     (regenerates agent/occam_bundle.py)
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "vendor" / "occam" / "solver"
OUT = ROOT / "agent" / "occam_bundle.py"

# Dependency order: a module only depends on those before it.
ORDER = [
    "events", "rhae", "action_ranker", "context_compression",
    "priority_tiers", "state_graph", "replay_explorer", "environments", "orchestrator",
]

HEADER = '''\
"""Bundled occam solver — flattened for the Kaggle self-contained splice.

Source: occam by Sean Donahoe (github.com/TheRealSeanDonahoe/occam), MIT License.
$0, no-LLM, deterministic reset-replay ARC-AGI-3 solver. This file is GENERATED by
scripts/bundle_occam.py from vendor/occam/solver/*.py — do not edit by hand.
"""
from __future__ import annotations
'''


def _strip(lines: list[str]) -> list[str]:
    out: list[str] = []
    i = 0
    while i < len(lines):
        ln = lines[i]
        s = ln.lstrip()
        if s.startswith("from __future__"):
            i += 1
            continue
        if s.startswith("from solver") or s.startswith("from .") or s.startswith("import solver"):
            # strip internal imports; consume continuation lines of a multi-line `import (`
            if "(" in ln and ")" not in ln:
                i += 1
                while i < len(lines) and ")" not in lines[i]:
                    i += 1
                i += 1  # skip the closing ")" line
            else:
                i += 1
            continue
        out.append(ln)
        i += 1
    return out


def main() -> None:
    parts = [HEADER]
    for mod in ORDER:
        body = (SRC / f"{mod}.py").read_text().splitlines()
        parts.append(f"\n# ========== occam/solver/{mod}.py ==========")
        parts.extend(_strip(body))
    OUT.write_text("\n".join(parts) + "\n")
    n = OUT.read_text().count("\n")
    print(f"[bundle_occam] wrote {OUT.relative_to(ROOT)} ({n} lines)")


if __name__ == "__main__":
    main()
